server:
  port: 8000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accounting_test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: hana
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    com.procarihana.accounting: DEBUG